### ISSUE TITLE
GA golang maintenance checklist

### ISSUE THREAD

**Issue by shaneutt** [kubernetes-sigs/gateway-api#1970]
In addition to `v1.0.0` being the first GA release of the APIs where we will want to maintain backwards compatibility thereafter, this will also be the first release of the Go libraries that will be in the same situation.

The purpose of this issue is to double check a few Golang related maintenance items before we release GA:

- [x] we've updated our version of Go in all places (images, e.t.c.) to the latest appropriate major/minor release
- [x] `go.mod` doesn't have any pins to any `main`/`master` branches
- [x] we're up-to-date on our k8s go dependencies
