### ISSUE TITLE
several documentation pages in need of v1alpha2 updates

### ISSUE THREAD

**Issue by shaneutt** [kubernetes-sigs/gateway-api#783]
**What would you like to be added**:

Several documentation pages need to be checked for updates for `v1alpha2` release, and patched accordingly.

**Why this is needed**:

These pages were identified in https://github.com/kubernetes-sigs/gateway-api/pull/778 and marked with a warning:

```
!!! danger "This page has not been updated for v1alpha2 yet."
```

The `v1alpha2` release can't move forward until all of these are checked and patched accordingly.

**TODO**

- [x] ~`site-src/v1alpha2/guides/getting-started.md`~ https://github.com/kubernetes-sigs/gateway-api/pull/786
- [x] ~`site-src/v1alpha2/guides/http-routing.md`~ https://github.com/kubernetes-sigs/gateway-api/pull/786
- [x] ~`site-src/v1alpha2/guides/multiple-ns.md`~ https://github.com/kubernetes-sigs/gateway-api/pull/807
- [x] ~`site-src/v1alpha2/guides/simple-gateway.md`~ https://github.com/kubernetes-sigs/gateway-api/pull/811
- [x] ~`site-src/v1alpha2/guides/tcp.md`~ https://github.com/kubernetes-sigs/gateway-api/pull/808
- [x] `site-src/v1alpha2/guides/traffic-splitting.md`
- [x] ~`site-src/v1alpha2/index.md`~ https://github.com/kubernetes-sigs/gateway-api/pull/782

**Comment by shaneutt** [comment]
I'm going to personally start reviewing and patching these.

**Comment by youngnick** [comment]
I think that @ccfishk was going to look at the traffic-splitting guide, is that right?

**Comment by ccfishk** [comment]
> I think that @ccfishk was going to look at the traffic-splitting guide, is that right?

Yes, working on traffic-splitting and simple-gateway guide.

**Comment by shaneutt** [comment]
Sounds good, I'll leave those two alone :+1:

**Comment by shaneutt** [comment]
Now that https://github.com/kubernetes-sigs/gateway-api/pull/786 is merged I'm going to take these three:

- `site-src/v1alpha2/guides/multiple-ns.md`
- `site-src/v1alpha2/guides/tcp.md`
- `site-src/v1alpha2/index.md`

I'll have a PR up for these soon :+1:

**Comment by shaneutt** [comment]
@ccfishk just wanted to check in on `site-src/v1alpha2/guides/traffic-splitting.md`

**Comment by robscott** [comment]
Missed that @ccfishk had already handled traffic splitting with https://github.com/kubernetes-sigs/gateway-api/pull/811, going to close this one out.

/close
